modLoader="javafml"
loaderVersion="[47,)"
license="BSD-3-Clause"

[[mods]]
modId="mclink"
version="${version}"
displayName="Tailcat for Minecraft (NeoForge)"
authors="Tailscale, DeepMind"
description='''Peer-to-peer LAN multiplayer over Tailscale Tailcat'''
logoFile="assets/mclink/textures/gui/sprites/tailcat.png"

[[dependencies.mclink]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mclink]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
